# Generated by Django 2.2.16 on 2022-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221111_2303'),
        ('reviews', '0003_alter_review_score'),
    ]

    operations = [
    ]
