# Generated by Django 2.2.16 on 2022-11-12 21:54

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20221113_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=13, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=reviews.models.UsernameField(help_text='Только буквы, цифры, @, +, -, _', max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
